// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/processing.proto

package processingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProcessingUnit_RegisterUser_FullMethodName = "/processing.ProcessingUnit/RegisterUser"
)

// ProcessingUnitClient is the client API for ProcessingUnit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProcessingUnit gRPC サービス定義
type ProcessingUnitClient interface {
	// ユーザ登録を処理ユニットに依頼
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
}

type processingUnitClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessingUnitClient(cc grpc.ClientConnInterface) ProcessingUnitClient {
	return &processingUnitClient{cc}
}

func (c *processingUnitClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, ProcessingUnit_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingUnitServer is the server API for ProcessingUnit service.
// All implementations must embed UnimplementedProcessingUnitServer
// for forward compatibility.
//
// ProcessingUnit gRPC サービス定義
type ProcessingUnitServer interface {
	// ユーザ登録を処理ユニットに依頼
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	mustEmbedUnimplementedProcessingUnitServer()
}

// UnimplementedProcessingUnitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProcessingUnitServer struct{}

func (UnimplementedProcessingUnitServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedProcessingUnitServer) mustEmbedUnimplementedProcessingUnitServer() {}
func (UnimplementedProcessingUnitServer) testEmbeddedByValue()                        {}

// UnsafeProcessingUnitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcessingUnitServer will
// result in compilation errors.
type UnsafeProcessingUnitServer interface {
	mustEmbedUnimplementedProcessingUnitServer()
}

func RegisterProcessingUnitServer(s grpc.ServiceRegistrar, srv ProcessingUnitServer) {
	// If the following call panics, it indicates UnimplementedProcessingUnitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProcessingUnit_ServiceDesc, srv)
}

func _ProcessingUnit_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingUnitServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProcessingUnit_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingUnitServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcessingUnit_ServiceDesc is the grpc.ServiceDesc for ProcessingUnit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcessingUnit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "processing.ProcessingUnit",
	HandlerType: (*ProcessingUnitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _ProcessingUnit_RegisterUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/processing.proto",
}
